### ISSUE TITLE
turn off options.replacePath

### ISSUE THREAD

**Issue by ganlanyuan** [unic/gulp-colorize-svgs#1]
Hey,
Thanks for your fantastic work! It really helps me a lot.
Is there a way to turn off `options.replacePath` if I just want to change the color?

**Comment by backflip** [comment]
Hey @ganlanyuan, I'm really sorry about the delay, did not see a notification.

In case this is still of interest: It should be possible to just return the original path:
```
replacePath: function(path, colorKey) {
	return path;
}
```

**Comment by ganlanyuan** [comment]
I see, thanks
