### ISSUE TITLE
Create npm package 

### ISSUE THREAD

**Issue by timothyk0908** [unic/gulp-colorize-svgs#2]
Hello,

I'm using your repo in one of my projects , could you please create an npm package , or do you mind if we do it ? 

Thank you very much,

Timothy

**Comment by backflip** [comment]
Sure, here you go: https://www.npmjs.com/package/gulp-colorize-svgs
Nice to know this is also of use outside of our company!

Cheers,
Thomas

**Comment by timothyk0908** [comment]
It is :) 

thank you so much ! 

Cheers,
Timothy
